services:
  app:
    container_name: app_container
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    command: bash -c "ruby server/src/http_server.rb"
    env_file:
      - .env
    depends_on:
      - db
    
  db:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: "${USER}"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "structure_my_day_development"
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    
volumes:
  postgres-data: 
