services:
  app:
    build: .
    environment:
      # Ensure your Ruby.rb app is configured to use these environment variables for the database connection
      POSTGRES_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_NAME: postgres
    ports:
      - 3000:3000
    volumes:
      - ./:/app
    
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432" # Optional: Expose PostgreSQL port only if you need to access it directly from the host

volumes:
  db-data: 
